name: Test List GitHub Models Action

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Test the action
        uses: ./
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          artifact-name: 'test-list-github-models'
          